# Generated by Django 3.2.7 on 2021-09-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictgame', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(fields=('player', 'question'), name='one_definition_per_question'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.UniqueConstraint(fields=('player', 'chose'), name='one_guess_per_question'),
        ),
    ]
